version: '3'
services:
  load_articles:
    image: data2knowledge/wheretolive-api:0.7.0
    container_name: load_articles
    external_links:
      - elastic1
      - elastic2
    volumes:
#      - /Users/fabiofumarola/articles:/opt/docker/backup
#      - /home/kdde:/opt/docker/backup
#    command: "-e prod_single -j LoadArticles"

networks:
networks:
  default:
    external:
      name: kddeenv_esnet
